apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumerinformationmodulesrv
    service: consumerinformationmodulesrv
  name: consumerinformationmodulesrv
spec:
  ports:
  - name: http
    port: {{.Values.REST_PORT}}
    targetPort: {{.Values.REST_PORT}}
  selector:
    app: consumerinformationmodule
