definitions:
  controller_echo.ListConsumerResponseFilterCompanyById:
    properties:
      consumer:
        items:
          $ref: '#/definitions/model.Consumer'
        type: array
    type: object
  controller_echo.ListConsumerResponseFindConsumer:
    properties:
      consumer:
        items:
          $ref: '#/definitions/model.Consumer'
        type: array
    type: object
  controller_echo.ListConsumerResponseViewAllConsumers:
    properties:
      consumer:
        items:
          $ref: '#/definitions/model.Consumer'
        type: array
    type: object
  model.Consumer:
    properties:
      address:
        type: string
      clientid:
        type: string
      clientname:
        type: string
      clientrepresentative:
        type: string
      consumerid:
        type: string
      consumername:
        type: string
      cspid:
        type: string
      dateofbirth:
        type: string
      fedexid:
        type: string
      objectuuid:
        type: string
      othernames:
        type: string
      ssn:
        type: string
    type: object
info:
  contact: {}
paths:
  /consumerinformationmodule/api/consumer:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: DeleteConsumers
      tags:
      - consumerinformationmodule
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller_echo.ListConsumerResponseViewAllConsumers'
      summary: ViewAllConsumers
      tags:
      - consumerinformationmodule
    post:
      consumes:
      - application/json
      parameters:
      - description: model.Consumer body data
        in: body
        name: body-param
        required: true
        schema:
          $ref: '#/definitions/model.Consumer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Consumer'
      summary: CreateConsumer
      tags:
      - consumerinformationmodule
    put:
      consumes:
      - application/json
      parameters:
      - description: model.Consumer body data
        in: body
        name: body-param
        required: true
        schema:
          $ref: '#/definitions/model.Consumer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Consumer'
      summary: EditConsumer
      tags:
      - consumerinformationmodule
  /consumerinformationmodule/api/consumer/profile:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' string consumerid query '
        in: query
        name: consumerid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller_echo.ListConsumerResponseFilterCompanyById'
      summary: FilterCompanyById
      tags:
      - consumerinformationmodule
  /consumerinformationmodule/api/consumerbyid:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' string consumerid query '
        in: query
        name: consumerid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller_echo.ListConsumerResponseFindConsumer'
      summary: FindConsumer
      tags:
      - consumerinformationmodule
swagger: "2.0"
